# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradN <- function(Model, Data, par, h = 1e-6, order = 1L) {
    .Call(`_YABS_gradN`, Model, Data, par, h, order)
}

harmwg <- function(Model, Data, Iterations, Status, InitialValues, Thinning, ACC, DevianceMat, LIV, Monitor, Mo0, samples, PPD, Adapt, Sigma) {
    .Call(`_YABS_harmwg`, Model, Data, Iterations, Status, InitialValues, Thinning, ACC, DevianceMat, LIV, Monitor, Mo0, samples, PPD, Adapt, Sigma)
}

harm <- function(Model, Data, Iterations, Status, InitialValues, Thinning, ACC, DevianceMat, LIV, Monitor, Mo0, samples, PPD, Adapt, Sigma) {
    .Call(`_YABS_harm`, Model, Data, Iterations, Status, InitialValues, Thinning, ACC, DevianceMat, LIV, Monitor, Mo0, samples, PPD, Adapt, Sigma)
}

gcharm <- function(Model, Data, Iterations, Status, InitialValues, Thinning, ACC, DevianceMat, h, LIV, Monitor, Mo0, samples, PPD, Adapt, Sigma) {
    .Call(`_YABS_gcharm`, Model, Data, Iterations, Status, InitialValues, Thinning, ACC, DevianceMat, h, LIV, Monitor, Mo0, samples, PPD, Adapt, Sigma)
}

ohss <- function(Model, Data, Iterations, Status, InitialValues, Thinning, ACC, DevianceMat, LIV, Monitor, Mo0, samples, PPD, Adapt) {
    .Call(`_YABS_ohss`, Model, Data, Iterations, Status, InitialValues, Thinning, ACC, DevianceMat, LIV, Monitor, Mo0, samples, PPD, Adapt)
}

nuts <- function(Model, Data, Iterations, Status, InitialValues, Thinning, thinned, postpred, Dev, Mon, Mo0, h = 1e-6, max_depth = 10L, Adapt = 1000L, target = 0.65) {
    .Call(`_YABS_nuts`, Model, Data, Iterations, Status, InitialValues, Thinning, thinned, postpred, Dev, Mon, Mo0, h, max_depth, Adapt, target)
}

samplingImportanceResampling <- function(MAP, VarCov, Model, Data, iterations) {
    .Call(`_YABS_samplingImportanceResampling`, MAP, VarCov, Model, Data, iterations)
}

sagva <- function(Model, Data, Iterations, Status, InitialValues, InitialCov, Thinning, thinned, postpred, Dev, Mon, h = 1e-4, learning_rate = -1.0, Stop_Tolerance = 1e-4, Min_Iterations = 200L, Patience = 50L, eig_floor = 1e-8) {
    .Call(`_YABS_sagva`, Model, Data, Iterations, Status, InitialValues, InitialCov, Thinning, thinned, postpred, Dev, Mon, h, learning_rate, Stop_Tolerance, Min_Iterations, Patience, eig_floor)
}

qnsagva <- function(Model, Data, Iterations, Status, InitialValues, InitialCov, Thinning, thinned, postpred, Dev, Mon, memory = 10L, h = 1e-4, damping = 0.2, learning_rate = -1.0, Stop_Tolerance = 1e-4, Min_Iterations = 200L, Patience = 50L, eig_floor = 1e-8) {
    .Call(`_YABS_qnsagva`, Model, Data, Iterations, Status, InitialValues, InitialCov, Thinning, thinned, postpred, Dev, Mon, memory, h, damping, learning_rate, Stop_Tolerance, Min_Iterations, Patience, eig_floor)
}

mcvi <- function(Model, Data, Iterations, Status, thinned, postpred, Dev, Mon, InitialValues, InitialCov, Thinning, T_mcmc = 3L, L_leapfrog = 3L, K_rb = 5L, h = 1e-4, learning_rate = 5e-3, spsa_scale = 1e-3, initial_epsilon = -1.0, Stop_Tolerance = 1e-4, Min_Iterations = 200L, Patience = 50L, grad_clip = 100.0) {
    .Call(`_YABS_mcvi`, Model, Data, Iterations, Status, thinned, postpred, Dev, Mon, InitialValues, InitialCov, Thinning, T_mcmc, L_leapfrog, K_rb, h, learning_rate, spsa_scale, initial_epsilon, Stop_Tolerance, Min_Iterations, Patience, grad_clip)
}

svgd <- function(Model, Data, Iterations, Status, InitialParticles, Thinning, thinned, postpred, Dev, Mon, step_size = 0.01, h_scale = 1.0, use_adam = TRUE, h_grad = 1e-4, Stop_Tolerance = 1e-4, Min_Iterations = 200L, Patience = 50L, grad_clip = 100.0) {
    .Call(`_YABS_svgd`, Model, Data, Iterations, Status, InitialParticles, Thinning, thinned, postpred, Dev, Mon, step_size, h_scale, use_adam, h_grad, Stop_Tolerance, Min_Iterations, Patience, grad_clip)
}

