# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcmcmwg <- function(Model, Data, Iterations, Status, Thinning, Acceptance, Dev, LIV, Mon, Mo0, thinned) {
    .Call(`_YABS_mcmcmwg`, Model, Data, Iterations, Status, Thinning, Acceptance, Dev, LIV, Mon, Mo0, thinned)
}

harm <- function(Model, Data, Iterations, Status, Thinning, Acceptance, Dev, LIV, Mon, Mo0, thinned) {
    .Call(`_YABS_harm`, Model, Data, Iterations, Status, Thinning, Acceptance, Dev, LIV, Mon, Mo0, thinned)
}

nutsda <- function(Model, Data, Iterations, Status, h, Thinning, Acceptance, Dev, M_adap, LIV, Mon, Mo0, thinned) {
    .Call(`_YABS_nutsda`, Model, Data, Iterations, Status, h, Thinning, Acceptance, Dev, M_adap, LIV, Mon, Mo0, thinned)
}

